FROM node:14-alpine

WORKDIR /app

RUN chown node:node /app

COPY --chown=node:node package*.json ./ 

USER node

RUN rm -rf package-lock.json
RUN rm -rf node_modules 
RUN npm install

COPY . .
COPY --chown=node:node . .

EXPOSE 3000

ENV MONGODB_USERNAME anhlongwin
ENV MONGODB_PASSWORD anhlongwin1901

CMD ["npm", "run", "start"]

